baseURL = "https://romantic-hodgkin-e6944c.netlify.app/"
languageCode = "en-us"
title = "Benwa Online"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  comment = "comments"

[permalinks]
  top = "/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true