baseURL = "https://romantic-hodgkin-e6944c.netlify.app/"
languageCode = "en-us"
title = "Benwa Online"

[permalinks]
  top = "/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true