version: '3'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./benwaonline/static:/www/benwa.online/static
            # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            # - ./nginx/conf.d:/etc/nginx/conf.d
            - conf:/etc/nginx/conf.d
            - ./nginx/vhost.d:/etc/nginx/vhost.d
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/logs:/var/log/nginx
            - certs:/etc/nginx/certs
        environment:
            - VIRTUAL_HOST=benwa.online
            - LETSENCRYPT_HOST=benwa.online

    nginx-gen:
        image: nginxproxy/docker-gen
        container_name: nginx-gen
        command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        restart: always 
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            # - ./nginx/conf.d:/etc/nginx/conf.d
            - conf:/etc/nginx/conf.d
            - ./nginx/vhost.d:/etc/nginx/vhost.d
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/logs:/var/log/nginx
            - certs:/etc/nginx/certs:ro
            - /tmp/templates:/etc/docker-gen/templates
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: "true"
    
    nginx-ssl:
        image: nginxproxy/acme-companion
        container_name: nginx-ssl
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/vhost.d:/etc/nginx/vhost.d
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/logs:/var/log/nginx
            - certs:/etc/nginx/certs:rw
            - acme:/etc/acme.sh
        environment:
            - "NGINX_PROXY_CONTAINER=nginx"
            - "NGINX_DOCKER_GEN_CONTAINER=nginx-gen"

    # nginx-ssl:
    #     image: jrcs/letsencrypt-nginx-proxy-companion:stable
    #     container_name: nginx-ssl
        # volumes:
        #     - /var/run/docker.sock:/var/run/docker.sock:ro
        #     - ./nginx/conf.d:/etc/nginx/conf.d
        #     - ./nginx/vhost.d:/etc/nginx/vhost.d
        #     - ./nginx/html:/usr/share/nginx/html
        #     - ./nginx/logs:/var/log/nginx
        #     - certs:/etc/nginx/certs:rw
    #     restart: always
        # environment:
        #     - "NGINX_PROXY_CONTAINER=nginx"
        #     - "NGINX_DOCKER_GEN_CONTAINER=nginx-gen"

    benwaonline:
        # depends_on:
        #     - nginx-ssl
        # image will change to something else
        image: klakegg/hugo:0.83.1-ext-alpine
        # entrypoint: hugo-official
        container_name: benwaonline
        # environment:
        #     - FRONT_HOST=https://benwa.online
        #     - VIRTUAL_HOST=benwa.online
        #     - LETSENCRYPT_HOST=benwa.online
        # command will change
        # command: server
        volumes:
            - ".:/src"
            - ./benwaonline/static:/src/public

volumes:
    certs:
    acme:
    conf:

networks:
    default:
        external:
            name: nginx-proxy
