version: '3'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs
            - ./nginx/logs:/var/log/nginx

    nginx-gen:
        image: nginxproxy/docker-gen
        container_name: nginx-gen
        command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        restart: always 
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx/logs:/var/log/nginx
            - /tmp/templates:/etc/docker-gen/templates
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: "true"
    
    nginx-ssl:
        image: nginxproxy/acme-companion
        container_name: nginx-ssl
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs:rw
            - acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./nginx/logs:/var/log/nginx

        environment:
            - "NGINX_PROXY_CONTAINER=nginx"
            - "NGINX_DOCKER_GEN_CONTAINER=nginx-gen"


    benwaonline-build:
        image: klakegg/hugo:0.83.1-ext-alpine
        container_name: benwaonline-build
        volumes:
            - ".:/src"
            - content:/src/public
    
    benwaonline-host:
        image: nginx:alpine
        container_name: benwaonline-host
        restart: unless-stopped
        expose:
            - "80"
            - "443"
        volumes:
            - content:/usr/share/nginx/html
        environment:
            - VIRTUAL_HOST=benwa.online
            - LETSENCRYPT_HOST=benwa.online

volumes:
    certs:
    acme:
    conf:
    vhost:
    html:
    content:

networks:
    default:
        external:
            name: nginx-proxy
