version: '3'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - ./nginx/logs:/var/log/nginx
            - certs:/etc/nginx/certs
        environment:
            - LETSENCRYPT_TEST=true
            - FRONT_HOST=https://benwa.online
            - VIRTUAL_HOST=benwa.online
            - LETSENCRYPT_HOST=benwa.online

    nginx-gen:
        image: nginxproxy/docker-gen
        container_name: nginx-gen
        command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        restart: always 
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - ./nginx/logs:/var/log/nginx
            - certs:/etc/nginx/certs:ro
            - /tmp/templates:/etc/docker-gen/templates
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: "true"
    
    nginx-ssl:
        image: nginxproxy/acme-companion
        container_name: nginx-ssl
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - ./nginx/logs:/var/log/nginx
            - certs:/etc/nginx/certs:rw
            - acme:/etc/acme.sh
        environment:
            - DEBUG=1
            - "NGINX_PROXY_CONTAINER=nginx"
            - "NGINX_DOCKER_GEN_CONTAINER=nginx-gen"


    benwaonline:
        image: klakegg/hugo:0.83.1-ext-alpine
        container_name: benwaonline
        # environment:
        #     - FRONT_HOST=https://benwa.online
        #     - VIRTUAL_HOST=benwa.online
        #     - LETSENCRYPT_HOST=benwa.online
        # command will change
        # command: server
        # expose:
        #     - "1313"
        volumes:
            - ".:/src"
            - html:/src/public

volumes:
    certs:
    acme:
    conf:
    vhost:
    html:

networks:
    default:
        external:
            name: nginx-proxy
